// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/shaojunda/Go-000/Week4/explorer/internal/biz"
	"github.com/shaojunda/Go-000/Week4/explorer/internal/data"
	"github.com/shaojunda/Go-000/Week4/explorer/internal/service"
)

// Injectors from wire.go:

func InitializeBookService() *service.BookService {
	db := data.NewDB()
	bookRepo := data.NewBookRepo(db)
	bookUsecase := biz.NewBookUsecase(bookRepo)
	bookService := service.NewBookService(bookUsecase)
	return bookService
}
